### ISSUE TITLE
readme里面的数据库文件链接好像出错了 请问能重新发一下吗

### ISSUE THREAD

**Issue by zeyang919** [AlbertoWang/springboot-58#1]
https://github.com/cncq-kycb/Springboot-TaoCheNet/blob/master/src/main/resources/58.sql 这个网页打不开了
尝试着用url连接数据库也都失败了

**Comment by AlbertoWang** [comment]
数据库的配置文件需要改成你自己的。在resources/application.yml当中

**Comment by zeyang919** [comment]
因为不太确定数据库的结构，所以可能搭建一个匹配的数据库比较慢。
请问可以给我发一个sql文件，让我测试一下吗？
只是想用来练练手，但是因为没有数据库 所以网页里都是空的 有点不知所措。

**Comment by AlbertoWang** [comment]
我不确定sql是否是最新的，因为这个项目后期有部分数据库更改与代码更改没有push。不过大部分都是可用的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cncq-kycb/Springboot-TaoCheNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 上午10:56
收件人:&nbsp;"cncq-kycb/Springboot-TaoCheNet"<Springboot-TaoCheNet@noreply.github.com&gt;;
抄送:&nbsp;"AlbertoWang"<albertowang@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cncq-kycb/Springboot-TaoCheNet] readme里面的数据库文件链接好像出错了 请问能重新发一下吗 (#1)





 
因为不太确定数据库的结构，所以可能搭建一个匹配的数据库比较慢。
 请问可以给我发一个sql文件，让我测试一下吗？
 只是想用来练练手，但是因为没有数据库 所以网页里都是空的 有点不知所措。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

58.sql (419.06M, 2020年11月13日 18:02 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=08353433dbc0aa8305d3e60b42385649040d5151525b5d021e5603505015505f0402190a010b004b510650555c5c500001515050643e64530b1b4742083812&code=3543d8df
